### ISSUE TITLE
Where are the 120+ Trained Agents?

### ISSUE THREAD

**Issue by vkakerbeck** [DLR-RM/rl-trained-agents#1]
Hi,

I'm sorry if I am just totally blind but I cannot find the 120+ Trained Agents that are mentioned in the https://github.com/DLR-RM/rl-baselines3-zoo readme. 
As far as I understood one can download the models using git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo
but there I only get a trained model for CartPole in ppo and a2c and Pendulum for sac. Where can I find the trained models for all the other environments?

Thank you for your help!

**Comment by araffin** [comment]
Hello,
sorry for the confusion, this is a remain from a copy paste...
The 120+ agents are currently in the rl zoo of SB2 (tensorflow): https://github.com/araffin/rl-baselines-zoo

I am actually waiting for SB3 v1.0 (which should released soon) to populate this repo.
You can watch the releases of SB3 and of the rl baselines3 zoo to be notified in time ;)

**Comment by vkakerbeck** [comment]
Thanks for your fast reply! I had actually seen those models in the SB2 rl zoo but couldn't get them to work with SB3, am I doing something wrong there?
SB3 seems to be looking for a zip folder containing pth files but the SB2 rl zoo provides pkl files. Is there some way to use the existing models with SB3?

**Comment by araffin** [comment]
Yes, but it needs some tweaks, see https://stable-baselines.readthedocs.io/en/master/guide/export.html#export-to-pytorch
the google colab i made in https://github.com/hill-a/stable-baselines/issues/372#issuecomment-504095491 only covers the part to convert from SB2 to PyTorch, you will need to take a look at 
https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters
to actually load those parameters into SB3.

Btw, if you write such migration script, this would be a valuable contribution for the project ;)

**Comment by vkakerbeck** [comment]
Thanks a lot for the links and your quick help! I will take a look at writing a migration script and hopefully I can come up with something worth contributing :)

**Comment by araffin** [comment]
Hello,
The pre-trained agents are coming ;)
See https://github.com/DLR-RM/rl-trained-agents/pull/2
