### ISSUE TITLE
HER not compatible with zoo/stable-baselines3

### ISSUE THREAD

**Issue by sweber1** [DLR-RM/rl-trained-agents#19]
I was trying to use the trained HER agents for Fetch tasks. But the 'her' implementation has changed in stable-baselines3 in PR 243 (https://github.com/DLR-RM/stable-baselines3/pull/243). It's no longer an algo, but instead just a type of replay buffer.

`python3 enjoy.py --algo her --env FetchSlide-v1` doesn't work anymore. 

I'm raising this issue to avoid other users wasting time until the configs are updated. My workaround was to downgrade stable-baselines3 and rl-baselines3-zoo to v1.0.0.

**Comment by araffin** [comment]
Hello,

> My workaround was to downgrade stable-baselines3 and rl-baselines3-zoo to v1.0.0.

you don't need that.

we kept the old policies, but for the new ones, you can find them in the TQC folder, for instance:
- https://huggingface.co/sb3/tqc-FetchSlide-v1
- https://huggingface.co/sb3/tqc-FetchPickAndPlace-v1

so now you need to do:
```
python3 enjoy.py --algo tqc --env FetchSlide-v1
```

They are all listed in our benchmark file:
- https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/benchmark.md
